apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "mysqldump.fullname" . }}"
  labels:
    snappyflow/compname: mysql_dnd
    snappyflow/appname: QA_DND-stage
    app: {{ template "mysqldump.name" . }}
    chart: {{ template "mysqldump.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.mysql.password }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
{{- end -}}
